language: java
sudo: false
addons:
  sonarcloud:
    organization: "malavasiale"
    token:
      secure: "30743ad2056573373b095e1717a4704ebc222093" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


